//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCUI.PS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PS.IPostService")]
    public interface IPostService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_PostDTO/Add", ReplyAction="http://tempuri.org/IServiceBaseOf_PostDTO/AddResponse")]
        DTOLayer.PostDTO Add(DTOLayer.PostDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_PostDTO/Add", ReplyAction="http://tempuri.org/IServiceBaseOf_PostDTO/AddResponse")]
        System.Threading.Tasks.Task<DTOLayer.PostDTO> AddAsync(DTOLayer.PostDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_PostDTO/Update", ReplyAction="http://tempuri.org/IServiceBaseOf_PostDTO/UpdateResponse")]
        DTOLayer.PostDTO Update(DTOLayer.PostDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_PostDTO/Update", ReplyAction="http://tempuri.org/IServiceBaseOf_PostDTO/UpdateResponse")]
        System.Threading.Tasks.Task<DTOLayer.PostDTO> UpdateAsync(DTOLayer.PostDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_PostDTO/Delete", ReplyAction="http://tempuri.org/IServiceBaseOf_PostDTO/DeleteResponse")]
        bool Delete(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_PostDTO/Delete", ReplyAction="http://tempuri.org/IServiceBaseOf_PostDTO/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_PostDTO/GetAll", ReplyAction="http://tempuri.org/IServiceBaseOf_PostDTO/GetAllResponse")]
        System.Collections.Generic.List<DTOLayer.PostDTO> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_PostDTO/GetAll", ReplyAction="http://tempuri.org/IServiceBaseOf_PostDTO/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DTOLayer.PostDTO>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_PostDTO/GetEntityById", ReplyAction="http://tempuri.org/IServiceBaseOf_PostDTO/GetEntityByIdResponse")]
        DTOLayer.PostDTO GetEntityById(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_PostDTO/GetEntityById", ReplyAction="http://tempuri.org/IServiceBaseOf_PostDTO/GetEntityByIdResponse")]
        System.Threading.Tasks.Task<DTOLayer.PostDTO> GetEntityByIdAsync(System.Guid Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPostServiceChannel : MVCUI.PS.IPostService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostServiceClient : System.ServiceModel.ClientBase<MVCUI.PS.IPostService>, MVCUI.PS.IPostService {
        
        public PostServiceClient() {
        }
        
        public PostServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DTOLayer.PostDTO Add(DTOLayer.PostDTO item) {
            return base.Channel.Add(item);
        }
        
        public System.Threading.Tasks.Task<DTOLayer.PostDTO> AddAsync(DTOLayer.PostDTO item) {
            return base.Channel.AddAsync(item);
        }
        
        public DTOLayer.PostDTO Update(DTOLayer.PostDTO item) {
            return base.Channel.Update(item);
        }
        
        public System.Threading.Tasks.Task<DTOLayer.PostDTO> UpdateAsync(DTOLayer.PostDTO item) {
            return base.Channel.UpdateAsync(item);
        }
        
        public bool Delete(System.Guid Id) {
            return base.Channel.Delete(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(System.Guid Id) {
            return base.Channel.DeleteAsync(Id);
        }
        
        public System.Collections.Generic.List<DTOLayer.PostDTO> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DTOLayer.PostDTO>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public DTOLayer.PostDTO GetEntityById(System.Guid Id) {
            return base.Channel.GetEntityById(Id);
        }
        
        public System.Threading.Tasks.Task<DTOLayer.PostDTO> GetEntityByIdAsync(System.Guid Id) {
            return base.Channel.GetEntityByIdAsync(Id);
        }
    }
}
